name: saltstack-webapp-formula
source: https://github.com/bechtoldt/saltstack-webapp-formula
summary: SaltStack Formula to set up and configure web applications
todo:
  - add instructions how to use formhelper, add information about it in the formula-docs (dependency), show up alternative?
  - 'table/ matrix: os/salt compatibility (dedicated file)'
  - add list of available states
  - add tests
  - chmod config files, etc.
